apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ecom-agent
  labels:
    app: ecom-agent
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ecom-agent
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000
